"""Added ward_slug

Revision ID: 2cdda9a93017
Revises: 377ac41d935d
Create Date: 2022-09-04 16:12:01.000593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdda9a93017'
down_revision = '377ac41d935d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_complaint_statuses_completed_status'), 'complaint_statuses', ['completed_status'], unique=False)
    op.create_index(op.f('ix_complaints_completed_status'), 'complaints', ['completed_status'], unique=False)
    op.add_column('wards', sa.Column('ward_slug', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_wards_ward_slug'), 'wards', ['ward_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wards_ward_slug'), table_name='wards')
    op.drop_column('wards', 'ward_slug')
    op.drop_index(op.f('ix_complaints_completed_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaint_statuses_completed_status'), table_name='complaint_statuses')
    # ### end Alembic commands ###
