"""modified like and dislike

Revision ID: 377ac41d935d
Revises: 9a53896571a4
Create Date: 2022-09-02 17:59:40.311625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377ac41d935d'
down_revision = '9a53896571a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'complaint_statuses', 'ward_servant_profiles', ['ward_servant_username'], ['username'])
    op.add_column('complaints', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('dislike_count', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('no_of_comments', sa.Integer(), nullable=True))
    op.drop_column('likes', 'like_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('like_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('complaints', 'no_of_comments')
    op.drop_column('complaints', 'dislike_count')
    op.drop_column('complaints', 'like_count')
    op.drop_constraint(None, 'complaint_statuses', type_='foreignkey')
    # ### end Alembic commands ###
