"""phone number constraint changed

Revision ID: 38b8a6d40836
Revises: 2cdda9a93017
Create Date: 2022-09-05 00:33:43.966957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b8a6d40836'
down_revision = '2cdda9a93017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
