"""Password field modified

Revision ID: 9a53896571a4
Revises: 473f0b2bb616
Create Date: 2022-09-01 15:34:01.975071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a53896571a4'
down_revision = '473f0b2bb616'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
